namespace PANEGamepad.Gamepad
{
    public enum GamepadCode
    {
        None = 0,
        DPadUp,
        DPadDown,
        DPadLeft,
        DPadRight,
        A,
        B,
        X,
        Y,
        LB,
        LT,
        LS,
        RB,
        RT,
        RS,
        Menu,
        View,
        Guide,
        LeftStickX,
        LeftStickY,
        LeftStickLeft,
        LeftStickRight,
        LeftStickUp,
        LeftStickDown,
        RightStickX,
        RightStickY,
        RightStickLeft,
        RightStickRight,
        RightStickUp,
        RightStickDown,
        Count,
        Start = Menu + Count,
        Back = View + Count,
        L1 = LB + Count,
        L2 = LT + Count,
        L3 = LS + Count,
        R1 = RB + Count,
        R2 = RT + Count,
        R3 = RS + Count,
        Up = DPadUp + Count,
        Down = DPadDown + Count,
        Left = DPadLeft + Count,
        Right = DPadRight + Count,
        LSLeft = LeftStickLeft + Count,
        LSRight = LeftStickRight + Count,
        LSUp = LeftStickUp + Count,
        LSDown = RightStickDown + Count,
        RSLeft = RightStickLeft + Count,
        RSRight = RightStickRight + Count,
        RSUp = RightStickUp + Count,
        RSDown = RightStickDown + Count
    }
}